"""UniFi Network API module."""

from __future__ import annotations

from .client import UniFiNetworkClient
from .models import (
    DEFAULT_SITE_REPORT_ATTRS,
    SITE_REPORT_INTERVALS,
    Client,
    ClientType,
    Device,
    DevicePort,
    DeviceState,
    DeviceType,
    FirewallRule,
    FirewallZone,
    LegacyOutletMetrics,
    LegacyPortMetrics,
    Network,
    NetworkPurpose,
    NetworkType,
    Outlet,
    PolicyBasedRoute,
    PortBytesMetrics,
    PortForward,
    Site,
    SiteHealth,
    SiteReportBucket,
    TrafficRule,
    VpnClient,
    WifiNetwork,
    WifiSecurity,
    parse_outlet_metrics,
)

__all__ = [
    "DEFAULT_SITE_REPORT_ATTRS",
    "SITE_REPORT_INTERVALS",
    "Client",
    "ClientType",
    "Device",
    "DevicePort",
    "DeviceState",
    "DeviceType",
    "FirewallRule",
    "FirewallZone",
    "LegacyOutletMetrics",
    "LegacyPortMetrics",
    "Network",
    "NetworkPurpose",
    "NetworkType",
    "Outlet",
    "PolicyBasedRoute",
    "PortBytesMetrics",
    "PortForward",
    "Site",
    "SiteHealth",
    "SiteReportBucket",
    "TrafficRule",
    "UniFiNetworkClient",
    "VpnClient",
    "WifiNetwork",
    "WifiSecurity",
    "parse_outlet_metrics",
]
